name: PR validation

on:
  pull_request:
    branches:
    - develop

jobs:
  build:
  
    env:
        BUILD_CONFIG: 'Release'
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
      
      - name: Restore
        run: dotnet restore 
        working-directory: src/
      
      - name: Build
        run: dotnet build -c ${{ env.BUILD_CONFIG }} --no-restore
        working-directory: src/
      
      - name: Test
        run: dotnet test -c ${{ env.BUILD_CONFIG }} --no-build --collect:"XPlat Code Coverage" --logger trx --results-directory coverage
        working-directory: src/
      
              
      - name: Create code coverage report
        run: |
            dotnet tool install -g dotnet-reportgenerator-globaltool
            reportgenerator -reports:$(Agent.WorkFolder)/**/coverage.cobertura.xml -targetdir:$(Build.SourcesDirectory)/CodeCoverage -reporttypes:'Cobertura'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2       
        with:
            recreate: true
            path: code-coverage-results.md

      - name: Write to Job Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY

 