name: PR validation

on:
  pull_request:
    branches:
    - develop

jobs:
  build:
  
    env:
        BUILD_CONFIG: 'Release'
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'
      - name: Restore
        run: dotnet restore 'src/*.sln'
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-restore --no-build